CREATE TABLE useraccounts(
userID int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
fname TINYTEXT NOT NULL,
lname TINYTEXT NOT NULL,
username TINYTEXT NOT NULL UNIQUE,
pin int(4) NOT NULL,
email TINYTEXT NOT NULL UNIQUE
)
